---

apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      terminationGracePeriodSeconds: 90
      containers:
        - name: webapp
          image: iad.ocir.io/gse00014528/axisdemo/sampleflaskapp:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: http
          livenessProbe:
            httpGet:
              path: /cities.json
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /cities.json
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
      imagePullSecrets:
        - name: ocir-secret
